services:
  _defaults:
    public: true

  ingenico.payment.connector:
    class: Ingenico\Payment\Connector

  ingenico.payment.alias:
    class: Ingenico\Payment\Alias

  ingenico.payment.payment:
    class: Ingenico\Payment\Payment

  ingenico.payment.total:
    class: Ingenico\Payment\Total

  ingenico.payment.reminder:
    class: Ingenico\Payment\Reminder
    arguments:
      - '@ingenico.payment.connector'

  ingenico.payment.actions:
    class: Ingenico\Payment\Services\Actions
    arguments:
      - '@request_stack'
      - '@ingenico.payment.connector'